### ISSUE TITLE
Support installation using Cocoapods

### ISSUE THREAD

**Issue by tomer1490** [c19354837/react-native-system-setting#10]
Hi,
I would like to be able to use the library on iOS using Cocoapods instead of `react-native link`.
The only requirement needed is adding a podspec file.

**Comment by c19354837** [comment]
Thank you and your awesome pr.

I will verify it and deploy it to Cocoapods.

**Comment by c19354837** [comment]
I can install by `pod 'RCTSystemSetting', :path => './node_modules/react-native-system-setting'` with your pr. 

I'm new to Cocoapods, so is it the right way to use it?

**Comment by tomer1490** [comment]
Yes. You can take a look at the official react-native docs: [https://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies](https://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies)

**Comment by c19354837** [comment]
Thank you!

**Comment by tomer1490** [comment]
Thanks, Can you please release a new version to npm?

**Comment by c19354837** [comment]
V 1.2.1 is available.
