### ISSUE TITLE
How to disabled screen setting of Android

### ISSUE THREAD

**Issue by Donhv** [c19354837/react-native-system-setting#13]
I want when call function switchLocation Location auto change and don't move to screen setting of Android.
Who can help me?

**Comment by c19354837** [comment]
Changing location programmatically is not user-friendly. You should guide user to the setting page, and let the user decide.

**Comment by Donhv** [comment]
@c19354837 java android i chang Location auto change. :(

**Comment by afilp** [comment]
I tried `switchLocation` but nothing happens. Any ideas why? I have Redmi Note 4, Android 6

**Comment by c19354837** [comment]
Does [the example](https://github.com/c19354837/react-native-system-setting/tree/master/examples/SystemSettingExample) work well?
