### ISSUE TITLE
AudioManager.FLAG_PLAY_SOUND and sound device when changing the volume

### ISSUE THREAD

**Issue by guiyom19** [c19354837/react-native-system-setting#15]
Hi and thank you for this great library.
On Android, could you please make AudioManager.FLAG_PLAY_SOUND as a parameter in your setVolume method in the SystemSetting.java ?
My point is that I don't want to have the device sound when changing the volume.

Thanks!

**Comment by c19354837** [comment]
It's spring festival now, and I'll do it in the next week.

**Comment by c19354837** [comment]
Which flag would you like to set? 

In my phone (Meizu m2 note, Android 5.1), `AudioManager.FLAG_PLAY_SOUND` doesn't work.

**Comment by guiyom19** [comment]
It works on a Samsung Galaxy A3 2017.
Line 197 am.setStreamVolume(volType, (int) (val * am.getStreamMaxVolume(volType)), AudioManager.FLAG_PLAY_SOUND); 
I just wanted to choose if it's AudioManager.FLAG_PLAY_SOUND or 0.
But meanwhile, a figered another solution and don't use react-native-system-setting anymore that why I closed this issue.
But maybe it could be usefull for somebody else.

**Comment by c19354837** [comment]
V 1.2.2 has published.

Now you can control the sound like this:
```javascript
SystemSetting.setVolume(0.5, {
    playSound: false
});
```

[API](https://github.com/c19354837/react-native-system-setting/blob/master/API.md) have updated.

Thanks for your feedback.
