### ISSUE TITLE
MPVolumeView UI visible

### ISSUE THREAD

**Issue by lgraubner** [c19354837/react-native-system-setting#17]
With the latest release the MPVolumeView UI is visible in the upper left corner. I can see the Airplay Button which is a little annoying. Should be fixable by adjusting the GCRect coordinates.

Great feature anyways!

**Comment by c19354837** [comment]
Thanks for your feedback, and V 1.2.3 fix it.

I hide the MPVolumeView. 

Now, It will show system volume UI by
```
setVolume(0.5, {
    showUI: true
})
```
Or show nothing with `{showUI: false}` if you just want to change volume in silence.

**Comment by c19354837** [comment]
Feel free to reopen it if you're still in the trouble

**Comment by Karanp13** [comment]
setVolume(0.5, {
    showUI: false
})

I need hide when user application on background. I tried but still shows MPVolumeVIew UI.
