### ISSUE TITLE
SystemSetting.isLocationEnabled() always return false

### ISSUE THREAD

**Issue by MatheusGit** [c19354837/react-native-system-setting#19]
SystemSetting.isLocationEnabled().then((enable)=>{
  console.log(enable);
})

Enabling is always false even when my location is turned on. Others functions works fine for me.

**Comment by c19354837** [comment]
Android or iOS? I need more information.

**Comment by AugustoAleGon** [comment]
For me it is just working when High Precision is ON

**Comment by c19354837** [comment]
Thanks for your feedback.

V1.2.4 has fixed it. Now it works on GPS and network both.

**Comment by MatheusGit** [comment]
Thanks, sorry I'm late. Good job!
