### ISSUE TITLE
Link on iOS without CocoaPods

### ISSUE THREAD

**Issue by SuhairZain** [c19354837/react-native-system-setting#20]
Hi,
We're using CocoaPods to install some of the dependencies in our app, along with some libraries that are manually linked. The reason is that some libraries have issues when linked via CocoaPods and in those cases, I fall back to manual installation. It fails for this library too, but I'm unable to find any manual installation steps. Is manual installation not supported at all?

EDIT:
I was able to get a successful build by adding `node-modules/react-native-system-setting/ios/RCTSystemSetting.xcodeproj` to Libraries. But now I'm getting an error `Native module cannot be null` when running the app, coming from `SystemSettting.js:11:21`. Is this because of an issue with linking the library?

**Comment by c19354837** [comment]
try this [linking-libraries-ios](https://facebook.github.io/react-native/docs/linking-libraries-ios.html)

**Comment by SuhairZain** [comment]
Hey @c19354837, thanks for that. Those steps worked. Thank you. :)
