### ISSUE TITLE
iOS simulator Volume up and down not dispatching volume change event

### ISSUE THREAD

**Issue by SuhairZain** [c19354837/react-native-system-setting#21]
Hi,
I'm testing this library on a simulator. I do have a device but due to some strange bug with XCode, I'm unable to test it on the device.

On the simulator, when I Increase/Decrease the volume (Cmd + (Up/Down)), I can see the ios volume changing. Also, when I play something in my app, the playback volume changes as well. However, no volume change events are getting dispatched. I tried the example app and it's the same there as well. I moved the slider and it doesn't affect the volume shown by the OS. If I change the volume using the shortcut, the slider isn't getting updated either.

The same code works perfectly on Android and also the getVolume function is working on both Android and iOS. It's just the listener that has an issue on iOS.

**Comment by c19354837** [comment]
All APIs about volume don't work well on iOS simulator. 

I have no idea about it, maybe you have to test it on a real device.
