### ISSUE TITLE
Couldn't find key playSound in dynamic object

### ISSUE THREAD

**Issue by alexanderwallin** [c19354837/react-native-system-setting#22]
Hello!

I get an error when trying to set the system volume.

```js
import SystemSetting from 'react-native-system-setting'

SystemSetting.setVolume(1, {
  playSound: false,
})
```

This throws the following error:

```
Couldn't find key playSound in dynamic object

getBoolean
ReadableNativeMap.java

setVolume
SystemSetting.java:198
```

![img_4782](https://user-images.githubusercontent.com/6952455/38308686-ce134ee4-380f-11e8-94f3-f05a87894c64.JPG)

This also happens if I leave out the options object altogether.

### Project info

react-native-system-setting 1.2.4
React Native 0.52.3
Android 5.1.1

SDK version in `node_modules/react-native-system-setting/android/build.gradle` has been overwritten to be:

```
android {
    compileSdkVersion 26
    buildToolsVersion "26.0.1"

    defaultConfig {
        minSdkVersion 22
        targetSdkVersion 26
    }
}
```

**Comment by c19354837** [comment]
V1.2.5 has been published.

Thanks again for your PR.
