### ISSUE TITLE
[Android] openWriteSetting() directs to apps list.

### ISSUE THREAD

**Issue by Sanglepp** [c19354837/react-native-system-setting#24]
Hi,

this is a good library but I noticed that when calling openWriteSetting() then the user is directed to the apps list. And when pressing back button, then the right app permissions page is displayed. 

I did some digging in the source and seems that in SystemSetting.java:179 switchSetting(SysSettings.WRITESETTINGS) is called, which seems to be the cause of the redirection to the apps list. 

```java
@ReactMethod
    public void openWriteSetting() {
        Intent intent = new Intent(SysSettings.WRITESETTINGS.action, Uri.parse("package:" + mContext.getPackageName()));
        mContext.getCurrentActivity().startActivityForResult(intent, SysSettings.WRITESETTINGS.requestCode);
        switchSetting(SysSettings.WRITESETTINGS); // is this line necessary?
    }
```

**Comment by c19354837** [comment]
You are right! 

I have no testing devices now. V1.2.5 will be published this weekend.

**Comment by c19354837** [comment]
V1.2.5 has been published.

Thanks for your feedback.

**Comment by Sanglepp** [comment]
Thank you. Tested it and all is good. Will close the issue.
