### ISSUE TITLE
Is there any way to silently switch Bluetooth and Airplane Mode ?

### ISSUE THREAD

**Issue by OlivierFreyssinet** [c19354837/react-native-system-setting#26]
Hey first of all, thank you for this useful package !

I noticed that there was a way to switch Wifi silently (ie without opening the Android System Setting Page) with the method switchWifiSilence(complete).

I would love to have the same method for Bluetooth and Airplane Mode, is there any way to do this ?

**Comment by OlivierFreyssinet** [comment]
Great thanks !

**Comment by c19354837** [comment]
V1.3.0 has been published!

good news: `switchBluetoothSilence()` is available
bad news:  there is no `switchAirplaneSilence()` for system limits.

see [Powerful API](https://github.com/c19354837/react-native-system-setting#powerful-api)

**Comment by OlivierFreyssinet** [comment]
Very good, thanks for the update !
