### ISSUE TITLE
Listening to bluetooth and wifi

### ISSUE THREAD

**Issue by OlivierFreyssinet** [c19354837/react-native-system-setting#27]
Hey,
I have an issue using listeners for bluetooth and wifi states. I'm listening to `EventWifiChange` and `EventBluetoothChange`,  but I noticed that the listeners are not active until I use the API's `SwitchWifiSilence()` or the equivalent for bluetooth.
On the other side, it works immediately with `addVolumeListener()`.
(I took the code from your example, and my implementation of listening to wifi and bluetooth states are directly inspired from your example).

After looking into the native code in `SystemSetting.java` I think that I understood the reason for this: 
`listenVolume(reactContext)` is called directly in the `SystemSetting()` constructor, but for wifi (resp. bluetooth), `listenWifiState()` is only called in ReactMethod `switchWifiSilence()`.

Is there a way to fix that ? Maybe by adding React Methods `listenWifiState()` and `listenBluetoothState()` or something like this ?

I hope what I say makes sense haha, I'm a total novice with react native and android development. Thanks for your attention.

**Comment by c19354837** [comment]
You are right. 

These events are originally for callback( call the `complete` after switch ), so I register the broadcast dynamically to avoid waste of system resources. (Some people may just want to change the volume by this lib).

I'll add some APIs to meet your requirements.

**Comment by c19354837** [comment]
All you want is in V1.4.1

see [API](https://github.com/c19354837/react-native-system-setting/blob/master/API.md)

**Comment by OlivierFreyssinet** [comment]
Thanks, it's working perfectly !
