### ISSUE TITLE
Using this library causes iOS app to be rejected from App Store

### ISSUE THREAD

**Issue by sunweiyang** [c19354837/react-native-system-setting#28]
I attempted to submit an app to the iOS App Store using `react-native-system-setting` and received this scary rejection:

```
Your app uses the "prefs:root=" non-public URL scheme, which is a private entity. The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change.

Continuing to use or conceal non-public APIs in future submissions of this app may result in the termination of your Apple Developer account, as well as removal of all associated apps from the App Store.

Next Steps

To resolve this issue, please revise your app to provide the associated functionality using public APIs or remove the functionality using the "prefs:root" or "App-Prefs:root" URL scheme.

If there are no alternatives for providing the functionality your app requires, you can file an enhancement request.
```

The only place in my app that uses the "prefs:root=" non-public URL scheme is in `react-native-system-setting`, specifically in `react-native-system-setting/ios/RTCSystemSetting.m` starting at line 55:

```
-(void)initSetting{
    BOOL newSys = [UIDevice currentDevice].systemVersion.doubleValue >= 10.0;
    setting = @{@"wifi": (newSys?@"App-Prefs:root=WIFI" : @"prefs:root=WIFI"),
                @"location": (newSys?@"App-Prefs:root=Privacy&path=LOCATION" : @"prefs:root=Privacy&path=LOCATION"),
                @"bluetooth": (newSys?@"App-Prefs:root=Bluetooth" : @"prefs:root=Bluetooth"),
                @"airplane": (newSys?@"App-Prefs:root=AIRPLANE_MODE" : @"prefs:root=AIRPLANE_MODE")
                };
}
```

This package is fantastic, but this problem must be addressed, or users of this package simply can't submit to the iOS App Store.

**Comment by c19354837** [comment]
Thanks for your feedback.

Do you need these APIs which start with `switch*`? (eg: `switchWifi()`)

**Comment by sunweiyang** [comment]
I'm personally currently using `react-native-system-setting` only for reading and setting speaker volume. Other users may need these APIs.

**Comment by c19354837** [comment]
You can modify your codes to solve it as a temporary solution. 

path:  `yourProject/node_modules/react-native-system-setting/ios/RTCSystemSetting.m`

```Objective-c
-(void)initSetting{
    setting = @{};
}
```

Now you can upload a new app to AppStore safely.

Of course, I'll provide a final solution for all people in the next few days.

**Comment by JobiJoba** [comment]
Funny, 

I just got rejected also for that ... :< 

Thanks for the workaround

**Comment by c19354837** [comment]
V1.4.0 is available.

Add new API for this issues: `setAppStore()`.

You should call `setAppStore(true)` when your app will be submitted to App Store. It will disable these APIs which start with `switch*`. See [App Store](https://github.com/c19354837/react-native-system-setting#app-store)

> Apple review the .ipa by some tools, so I encode the private entity by base64 to avoid these static checking. See [How does Apple know you are using private API?
](https://stackoverflow.com/questions/2842357/how-does-apple-know-you-are-using-private-api)
>
> And I disable `switch*` function to avoid the potential runtime checking.

**Comment by SuhairZain** [comment]
@c19354837 Hi, I'm using this library only for listening to volume level changes and I got a rejection for the reason stated in this issue. Would just calling setAppStore(true) once in the app fix this issue, at least from this library?

**Comment by c19354837** [comment]
Which version do you use?  And I need the detail rejection content.

**Comment by c19354837** [comment]
You have to upgrade to >= 1.4.0. 

And I get an issues #55 about App Store.

**Comment by SuhairZain** [comment]
What about concealing the usage of private APIs as communicated by Apple team? Do you think it'd be an issue?

Regarding the issue with BT permission, I did get that as a reason for rejection for an earlier build. When I added a string for permission, it got solved.

**Comment by c19354837** [comment]
I did not receive any issues about the rejection from App Store since 1.4.0, so I think it works. 

If you still get a rejection after upgrade to latest version, please let me know.

**Comment by SuhairZain** [comment]
@c19354837 It looks like a good fix. We're using a fork in which I removed those lines right now. We'll make another release in under a week and will let you know how it goes. Thanks.

**Comment by SuhairZain** [comment]
@c19354837 When I run `nm __BUILD_DIR__/libRCTSystemSetting.a`, I can no longer see the `initSetting` method. I believe this issue has been solved. Thanks for the excellent fix.
