### ISSUE TITLE
Got UnExpected token error while using react-native-system-setting

### ISSUE THREAD

**Issue by BeckhamVinoth** [c19354837/react-native-system-setting#3]
Unexpected token (53:15)
  51 |   };
  52 | 
> 53 |   SystemSetting.isLocationEnabled().then((enable)=>{
     |                               ^
  54 |     const state = enable ? 'On' : 'Off';
  55 |     console.log('Current location is ' + state);
  56 | })

what is the fix for that ?

**Comment by c19354837** [comment]
need more codes

**Comment by c19354837** [comment]
Have you solved it yet?

**Comment by c19354837** [comment]
Feel free to reopen it if you're still in the trouble
