### ISSUE TITLE
Listening when Location change

### ISSUE THREAD

**Issue by havinhthai** [c19354837/react-native-system-setting#30]
## Version
react v16.3.1
react-native v0.55.4
react-native-system-setting v1.4.1

## Issue
I readed [API docs](https://github.com/c19354837/react-native-system-setting/blob/master/API.md), but It hasn't method to listening when location change.
So, have other way to know when location change?

Thank you.

**Comment by c19354837** [comment]
V1.4.2 add new API: `addLocationListener()` & `addAirplaneListener()`, see [API docs](https://github.com/c19354837/react-native-system-setting/blob/master/API.md).
