### ISSUE TITLE
Module RCTSystemSetting requires main queue setup 

### ISSUE THREAD

**Issue by blolo** [c19354837/react-native-system-setting#33]
getting this warning when i run the app on my device. 
Module RCTSystemSetting requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.

**Comment by c19354837** [comment]
Thanks for posting this. What's your RN version?

**Comment by blolo** [comment]
Hello, its 
"name": "react-native",
 "version": "0.55.3",

**Comment by c19354837** [comment]
V1.4.3 is available
