### ISSUE TITLE
Selected location mode in isLocationEnabled callback 

### ISSUE THREAD

**Issue by aliozinan** [c19354837/react-native-system-setting#35]
Hi, thanks for this great module first of all. I'm trying to use FusedLocation to get & follow the device location upon having the location setting switched on and getting the necessary permisson from the user (on Android). All is working ok except when the user selects a different mode than high accuracy. Is it possible if isLocationEnabled callback would provide the selected mode so that the we can redirect the user to right setting?

**Comment by c19354837** [comment]
There are 4 modes: `gps & network`, `gps only`,` network only`, `off`.

Is this what you want?

**Comment by aliozinan** [comment]
Yes, I want to get the mode user selects on the gps settings page and returns to my app on this call back, so I can show a warning that "high accuracy" (gps & network) will be recommended to use the app, in short words.

**Comment by c19354837** [comment]
I'll add a new API like `getLocationMode() => number`and the return code could be one of `0` - 'off', `1` - 'gps', `2` - 'network', `3` - 'gps & network'

> For backward compatibility, I cannot change the `isLocationEnabled`.

**Comment by aliozinan** [comment]
This would be great. I'll be following the updates. Thanks!

**Comment by c19354837** [comment]
V1.4.4 is available!  

Now you can use `getLocationMode()` instead of `isLocationEnable()`

**Comment by aliozinan** [comment]
Hi, re-opening the issue for another question about the topic : is it possible to have a listener for the location mode change? Right now I'm able to listen if the location setting is switched on/off but not for the location mode setting we had discussed here before.

**Comment by aliozinan** [comment]
Update : we have the SystemSetting.switchLocation method to take the user to the location settings page to ask them to turn on the location. On Android, location mode setting is also accessed from here by touching Location Mode. Is it possible to have a method that could directly take the user to this Location Mode setting page? If I knew native languages, I would definitely ask for a PR :)

**Comment by c19354837** [comment]
`addLocationModeListener()` is available in V1.7.2

**Comment by aliozinan** [comment]
greatly appreciated, thanks a lot! :)
