### ISSUE TITLE
isLocationEnabled and getLocationMode

### ISSUE THREAD

**Issue by blolo** [c19354837/react-native-system-setting#36]
Hello,

I'm trying to get the location permission status. I did try isLocationEnabled and  getLocationMode on iOS:

1) Is there away to tell if the user enabled the 'Always' vs 'While using the app'  option ? right now all I'm getting is 1 or 0  

2) accessing isLocationEnabled or getLocationMode always returns 1 regardless of my app settings selection

I'm using   
-  "react-native-system-setting": "^1.4.4"
- "react": "^16.3.2",
- "react-native": "0.55.3",

**Comment by c19354837** [comment]
Maybe [react-native-location](https://github.com/timfpark/react-native-location) or [react-native-permissions](https://github.com/yonahforst/react-native-permissions) can help you.

Both `isLocationEnabled` and `getLocationMode` return the **system location status**,  not the app.
