### ISSUE TITLE
isAirplaneEnabled always return true

### ISSUE THREAD

**Issue by DCKT** [c19354837/react-native-system-setting#37]
Hello,

On **iOS only** , `isAirplaneEnabled()` always return true.
It works perfectly on Android. Maybe a config issue ? 

Thanks 😄

**Comment by c19354837** [comment]
Have you run the [example](https://github.com/c19354837/react-native-system-setting/tree/master/examples/SystemSettingExample) ?

It works fine in my iPhone 7 plus (iOS 11.3.1), how about your test device?

**Comment by DCKT** [comment]
Hi @c19354837 

I does compile on the simulator but not on my test device, I have this error : 
![capture d ecran 2018-06-04 a 10 47 11](https://user-images.githubusercontent.com/1548421/40907595-a5546e98-67e4-11e8-92f6-778d3a1ba82f.png)

**Comment by c19354837** [comment]
Some APIs may not work well in simulator, and you should test in the physical device.

The error is React-Native's bug,  [see this PR](https://github.com/facebook/react-native/pull/18869)

I just change the code to:

```objective-c
static NSString *RCTCacheKeyForImage(NSString *imageTag, CGSize size, CGFloat scale,
                                     RCTResizeMode resizeMode, NSString *responseDate)
{
    return [NSString stringWithFormat:@"%@|%g|%g|%g|%lld|%@",
            imageTag, size.width, size.height, scale, (long long)resizeMode, responseDate];
}
```

**Comment by DCKT** [comment]
Yes I succeeded to make it compile and I have the same behavior : here is a screenshot 

![img_0013](https://user-images.githubusercontent.com/1548421/40962630-569be75a-68a6-11e8-928f-1a829f1a2883.PNG)

As you can see, the airplane mode is not enabled and it says it's "On". Is it normal, when I want to toggle the switch it send me to the bluetooth settings ?

**Comment by c19354837** [comment]
It's really strange.

I'll try to find a iPhone with iOS 10. It may take some time.

> For some iOS's limits, this lib just opens the Settings app whit the last page that you open.

**Comment by DCKT** [comment]
Thanks for your quick answers 😄

**Comment by c19354837** [comment]
I think I get it.

I get airplane's status by:

```objective-c
NSString * radio = [[CTTelephonyNetworkInfo alloc] init].currentRadioAccessTechnology;
bool isEnabled = radio == nil;
```
and the `currentRadioAccessTechnology` means `The current radio access technology the device is registered with`.

Normally, if your device has no SIM,  `isAirplaneEnabled()` always return `true`. 

There is no official API which can get airplane mode directly.  

Here are [some discussions](https://stackoverflow.com/questions/31067713/how-can-i-know-airplane-mode-on-or-off-in-ios?noredirect=1&lq=1). 

---

And 

>Is it normal, when I want to toggle the switch it send me to the bluetooth settings ?

It's a bug in iOS 10, and it's normal in iOS 11 for some system limits. Next version will fix it.

**Comment by DCKT** [comment]
Hi @c19354837 

Thanks a lot for your investigations ! I will find a device with a SIM card. 
I think you can add this to the README 😄

**Comment by c19354837** [comment]
V1.4.6 is available.

fix bug: `switchAirplane()` will open Bluetooth Setting Page for iOS.

Also I update the [README](https://github.com/c19354837/react-native-system-setting#usage) & [API](https://github.com/c19354837/react-native-system-setting/blob/master/API.md).

Thanks for your work.
