### ISSUE TITLE
App crashes on Android devices if holding (changing) volume during start up

### ISSUE THREAD

**Issue by shadowcatx** [c19354837/react-native-system-setting#39]
Hi Ninty, 

Thanks for creating this library!
A bug report (and a potential fix):

#### Issue description
RNSS will cause crashes on Android devices if the volume is changed during app startup.

#### Steps to reproduce the issue
1. Holding on volume up/down
2. Start the app
Tested on: Huawei Y6, Samsung J5, Samsung Galaxy S9, Samsung Galaxy Note 9

#### What's the expected result?
- App launches

#### What's the actual result?
- App crashes

#### Error log
Caused by java.lang.RuntimeException 
Tried to access a JS module before the React instance was fully set up. Calls to ReactContext#getJSModule should only happen once initialize() has been called on your native module.

####
The issue happens because users are able to interact with volumes before react is fully set up. That would cause a runtime exception. 
I've created a PR with an empty try-catch to address this issue.

Regards,
Samuel

**Comment by shadowcatx** [comment]
Thank you Ninty!

**Comment by c19354837** [comment]
V1.4.5 has been published!
