### ISSUE TITLE
Galaxy Tab error

### ISSUE THREAD

**Issue by TapaniAla** [c19354837/react-native-system-setting#4]
This package is probably not intended to be used with tabs but I get the following error: 
"Cannot read property 'setScreenMode' of undefined" coming from line 41 of SystemSetting.js

**Comment by TapaniAla** [comment]
Yes I did. Is there some easy way to check that react-native link succeeded?

**Comment by c19354837** [comment]
Can you [run the example](https://github.com/c19354837/react-native-system-setting#run-example)? 

Example has linked. You can check these file:

1. [projectRoot/android/settings.gradle](https://github.com/c19354837/react-native-system-setting/blob/master/examples/SystemSettingExample/android/settings.gradle#L2)

```
include ':react-native-system-setting'
project(':react-native-system-setting').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-system-setting/android')
```
2. [projectRoot/android/app/build.gradle](https://github.com/c19354837/react-native-system-setting/blob/master/examples/SystemSettingExample/android/app/build.gradle#L129)

```
compile project(':react-native-system-setting')
```
3. [projectRoot/android/app/src/main/java/com/systemsettingexample/MainApplication.java](https://github.com/c19354837/react-native-system-setting/blob/master/examples/SystemSettingExample/android/app/src/main/java/com/systemsettingexample/MainApplication.java#L27)

```
new SystemSettingPackage()
```

**Comment by TapaniAla** [comment]
I think the answer is here "If you need to include a library which includes react-native link in its install instructions, there's a good chance you need to eject from CRNA" from https://github.com/react-community/create-react-native-app/blob/master/EJECTING.md. I will check later.

**Comment by TapaniAla** [comment]
This solved my issue so I should eject from CRNA in order to use react-native link.

**Comment by c19354837** [comment]
Thank for your feedback. And I add a note for CRNAer in readMe to 
keep them from this kind of problem.
