### ISSUE TITLE
Undefined is not an object (evaluating 'SystemSettingNative.setVolume')

### ISSUE THREAD

**Issue by Rumidom** [c19354837/react-native-system-setting#40]
i have just detached an expo project to be able to set the global volume ( i have never done it before), react-native link seems to work ok but when i try to use the setVolume method i get this error, am i doing something wrong? (I have also tried to link the library manually with no luck)

```javascript 
import SystemSetting from 'react-native-system-setting';

export default class DispositivoGenerico extends React.Component{
  
  MudaVolume(InputValue){
  var oldMax = 255;
  var oldMin = 0;
  var newMax = 100;
  var newMin = 0;
  var oldRange = oldMax - oldMin
  var newRange = newMax - newMin

  var newValue = ((InputValue - oldMin) * newRange / oldRange) + newMin;
  
  SystemSetting.setVolume(newValue);
  this.props.OnValueChangeSlider(InputValue);
  }


```
...
![screenshot_20180606-154953](https://user-images.githubusercontent.com/1103035/41059256-5e8345ec-69a2-11e8-8a8a-fb1dadb14e00.png)

**Comment by c19354837** [comment]
Thanks for your feedback.

I'll test this lib by expo.

**Comment by c19354837** [comment]
After several days of hard work, finally `exp detach` succeeded.

Then link it by `react-native link`, it shows:

```
rnpm-install info Linking react-native-system-setting android dependency
rnpm-install info Platform 'android' module react-native-system-setting has been successfully linked
```

I run the app by Android Studio, and it works well. 

Do you link successfully? Or [link manually](https://github.com/c19354837/react-native-system-setting#android)

**Comment by Rumidom** [comment]
thanks for replying! i did link successfully and checked everything manually, but couldn't get it to work, i ended up giving up on exp detach, and started from scratch with` react-native init` , its working just fine there
