### ISSUE TITLE
Android: `getAppBrightness` and `getBrightness` always return the same number

### ISSUE THREAD

**Issue by derrickbeining** [c19354837/react-native-system-setting#47]
Device: Nexus 69
OS: Android 8.0.0
`package.json`:
```json
{
    "dependencies": {
        "react-native": "^0.51.0",
        "react-native-system-setting": "^1.5.0",
    }
}
```

No matter what the device's brightness is set to, when I open my app, `getAppBrightness` and `getBrightness` always resolve to the same number. This isn't the intended behavior is it? Any idea what I can do to fix it?

**Comment by derrickbeining** [comment]
Ah, never mind. Just realized it is because my phone was automatic brightness turned on. It works correctly when it's turned off.

**Comment by c19354837** [comment]
And you can get&set screen mode by `getScreenMode()` & `setScreenMode()`, see [API](https://github.com/c19354837/react-native-system-setting/blob/master/API.md)

> `setBrightnessForce()` will change the screen mode to `manual` first
