### ISSUE TITLE
Switches between Android volumes

### ISSUE THREAD

**Issue by lgraubner** [c19354837/react-native-system-setting#5]
Android has four different volumes (Media, Sound, Notifications, System). It seems like I get always the "active" volume, but this switches quite often. How to get/set a specific volume?

**Comment by c19354837** [comment]
`getVolume()` return the "Music" volume actually, [see code](https://github.com/c19354837/react-native-system-setting/blob/master/android/src/main/java/com/ninty/system/setting/SystemSetting.java#L147)

I consider to extended it. And it will look like `getVolume(type:String)`, so you can get the specific volume. The `type` should be one of these (copy from Android open source codes):

```java
/** The audio stream for phone calls */
public static final int STREAM_VOICE_CALL = AudioSystem.STREAM_VOICE_CALL;
/** The audio stream for system sounds */
public static final int STREAM_SYSTEM = AudioSystem.STREAM_SYSTEM;
/** The audio stream for the phone ring */
public static final int STREAM_RING = AudioSystem.STREAM_RING;
/** The audio stream for music playback */
public static final int STREAM_MUSIC = AudioSystem.STREAM_MUSIC;
/** The audio stream for alarms */
public static final int STREAM_ALARM = AudioSystem.STREAM_ALARM;
/** The audio stream for notifications */
public static final int STREAM_NOTIFICATION = AudioSystem.STREAM_NOTIFICATION;
```

**Comment by lgraubner** [comment]
That would be awesome. Do you already know when this will be available (approximately)?

**Comment by c19354837** [comment]
Two hours will be ok. I'm doing this

**Comment by c19354837** [comment]
V 1.0.8 has published!

I have updated the example and screenshot, and you will find the different

[API](https://github.com/c19354837/react-native-system-setting/wiki/API#api) is refreshed too.

I need to sleep now😪

**Comment by lgraubner** [comment]
Awesome, thank you! Works as far as I tested.
