### ISSUE TITLE
For RN 0.56.0: SDK Build Tools revision (23.0.1) is too low

### ISSUE THREAD

**Issue by sunweiyang** [c19354837/react-native-system-setting#51]
On RN 0.56.0, when trying to build Android app using `react-native-system-setting`, I see the following error output:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-system-setting'.
      > The SDK Build Tools revision (23.0.1) is too low for project ':react-native-system-setting'. Minimum required is 25.0.0
```

As of RN 0.56.0, the Android SDK versions used have been changed to the following:
```
    buildToolsVersion = "26.0.3"
    minSdkVersion = 16
    compileSdkVersion = 26
    targetSdkVersion = 26
    supportLibVersion = "26.1.0"
```

It seems like `react-native-system-setting` needs to be updated.

**Comment by c19354837** [comment]
V1.5.2 is available. 

I've update these properties, see this PR [Use project-wide properties and new dependency](https://github.com/c19354837/react-native-system-setting/pull/46)
