### ISSUE TITLE
ios brightness not working

### ISSUE THREAD

**Issue by neo125874** [c19354837/react-native-system-setting#52]
as title, 
the code works on Android, but not affecting iOS, 
any idea? thanks in advance.

**Comment by c19354837** [comment]
I need your phone info.

Does the [example](https://github.com/c19354837/react-native-system-setting/tree/master/examples/SystemSettingExample) work?

**Comment by neo125874** [comment]
@c19354837 I tried your example run on ios simulator, 
but still not working while I drag the brightness bar down or up.

**Comment by neo125874** [comment]
@c19354837 I used the ios 11.4 iphone6 simulator, thanks.

**Comment by c19354837** [comment]
This lib just works in physical device for some system limits.

**Comment by neo125874** [comment]
@c19354837 I tried the example on my iphone8 11.3 it worked, but my project still not working with this lib.

**Comment by c19354837** [comment]
Any error log?

**Comment by neo125874** [comment]
@c19354837 nope, and the app didnot crash too. 
would it be related to the old react native version?

**Comment by c19354837** [comment]
I write this lib from RN 0.44, and update to 0.56 a few days ago. It should works fine for old version.

Can you write a demo to reproduce this question?

**Comment by neo125874** [comment]
@c19354837 thanks for your quickly response, it's my problem, 
it worked on my debug version, 
cause of the release  version would be updated by my code-push
(which contained the previous code). 
many many thanks.
