### ISSUE TITLE
Warning about Bluetooth Permission when submitting app to iOS App Store

### ISSUE THREAD

**Issue by dpogoda** [c19354837/react-native-system-setting#55]
After submitting my app with `react-native-system-setting 1.5.3` to the iOS App Store I received the following mail:

> Dear Developer,
> We identified one or more issues with a recent delivery for your app. Please correct the following issues, then upload again.
> Missing Purpose String in Info.plist File - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSBluetoothPeripheralUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data will be required to include a purpose string.If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).
> Best regards,
> The App Store Team

Since I don't use Bluetooth anywhere in the app, I guess it's because this package can manage bluetooth as well. 
Does anyone else have a similar problem?

PS: I used `setAppStore(true)`.

**Comment by c19354837** [comment]
You can add `NSBluetoothPeripheralUsageDescription` in your `Info.plist` as a workaround. [Like this](https://stackoverflow.com/questions/44003952/app-rejected-missing-info-plist-key-nsbluetoothperipheralusagedescription-but)

I'll try to find a final solution.

**Comment by prakashw3expert** [comment]
Yes, i'm facing the same issue. In app i need only control value while not using bluetooth. After adding purpose string still apple rejected app.

> We identified one or more issues with a recent delivery for your app, "FacilGo®". Please correct the following issues, then upload again.
> 
> Missing Purpose String in Info.plist File - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSBluetoothPeripheralUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data will be required to include a purpose string.If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).

**Comment by c19354837** [comment]
V1.6.0 is available!

For bluetooth issues, see [this](https://github.com/c19354837/react-native-system-setting/blob/master/AppStore.md)

**Comment by c19354837** [comment]
V1.7.0 remove bluetooth codes by default. I think it's more friendly for you who don't need bluetooth. See [change log](https://github.com/c19354837/react-native-system-setting/blob/master/CHANGELOG.md)

> I also disable some other APIs by default in V1.7.0 You can enable it by [this](https://github.com/c19354837/react-native-system-setting/blob/master/iOS.md#ios)
