### ISSUE TITLE
This library contains code that will lead to a permanent rejection of apps binary by apple

### ISSUE THREAD

**Issue by JAStanton** [c19354837/react-native-system-setting#58]
You should not base64 / obfuscate a private library call:
https://github.com/c19354837/react-native-system-setting/blob/master/ios/RTCSystemSetting.m#L70-L73

Originally filed and "fixed" here: https://github.com/c19354837/react-native-system-setting/issues/28

If it's not caught now it _will_ be caught soon. Calling a private library is one thing, but getting a notice about it and then obfuscating the call and trying again is a sure fire way to get permanently rejected.

I do not advise anyone include this library or risk getting your app banned. The warning from apple mentioned doing exactly what you decided as safe, saying it in fact is not safe:

> Continuing to use or *conceal* non-public APIs in future submissions of this app may result in the *termination of your Apple Developer account*, as well as *removal of all associated apps from the App Store.*

**Comment by c19354837** [comment]
Thanks for you feedback.

I consider to solve it by preprocessor macros which can remove codes in compiling, so it's safe for App Store.

> I keep these private APIs for enterprise account to get better experience.

**Comment by JAStanton** [comment]
I see that your documentation you mentioned private APIs and that they are dangerous. This warning is not enough and base64 encoding the names is easy to detect

Apple will detect the base64 encoded names even if the libraries aren't being called, and likely someone will not read your warning and will have all their apps banned. 

Not safe for this to be in the source code.

**Comment by c19354837** [comment]
What an impressive name!

I would implement it in the next version.

**Comment by c19354837** [comment]
V1.7.0 is available. It's a AppStore-friendly version. 

I remove some dangerous codes by preprocessor macros, 
see [detail](https://github.com/c19354837/react-native-system-setting/blob/master/iOS.md#ios)

> I name it `PRIVATE_API`. You have to add it by reading the [doc](https://github.com/c19354837/react-native-system-setting/blob/master/iOS.md#ios) which I think you already know what you are doing.
