### ISSUE TITLE
isLocationEnabled() resolves with 'enabled' when in fact the phone's Location settings are disabled

### ISSUE THREAD

**Issue by thomasmarkiewicz** [c19354837/react-native-system-setting#59]
It works well on the iOS devices I've tested with, on the Android emulators, and on LineageOS 14.x Android phone.

On the Samsung Galaxy S8 (SM-G950U1) running Android 8.0.0 with Android security patch level from September 1, 2018, isLocationEnabled() resolves with 'enabled' when in fact the phone's Location settings are disabled.

This is for version 1.6.0

**Comment by c19354837** [comment]
Thanks for your feedback!

I get the location status by:

```java
LocationManager lm = (LocationManager) mContext.getApplicationContext().getSystemService(Context.LOCATION_SERVICE);
lm.isProviderEnabled(LocationManager.GPS_PROVIDER) || lm.isProviderEnabled(LocationManager.NETWORK_PROVIDER);
```

It looks like `lm.isProviderEnabled()` doesn't work well in S8 , can you test these java codes yourself? Or I provide a test app for you?

**Comment by thomasmarkiewicz** [comment]
I can debug.

Looking at your code above, is there a reason not to call lm.isLocationEnabled() instead?

https://developer.android.com/reference/android/location/LocationManager.html#isLocationEnabled()

**Comment by c19354837** [comment]
Glad to receive your response from Github notification by email, while I find nothing here (maybe I should open an issue for github 😝), so I paste your message again:

```
from Thomas Markiewicz:

I can debug.
Looking at your code above, is there a reason not to call lm.isLocationEnabled() instead?
https://developer.android.com/reference/android/location/LocationManager.html#isLocationEnabled()
```

`isLocationEnabled` is added in API 28( Android 9), so I cannot call this API. Can you tell me the result for `lm.isProviderEnabled(LocationManager.GPS_PROVIDER)` and `lm.isProviderEnabled(LocationManager.NETWORK_PROVIDER)` when the location is disabled?

**Comment by thomasmarkiewicz** [comment]
I debugged your sample code on my phone and both GPS_PROVIDER and NETWORK_PROVIDER return "false" when location is disabled.  

Since that appears to be working correctly, I re-ran my app and that also works correctly now.

I'm not sure what changed.  I did uninstall a "Fake GPS" app I was using for testing and rebooted the phone - it's possible that that is what was causing the original issue.

Since this is working for me now, we can close this issue.

**Comment by lstaniszewski** [comment]
```java
LocationManager lm = (LocationManager) mContext.getApplicationContext().getSystemService(Context.LOCATION_SERVICE);
lm.isProviderEnabled(LocationManager.GPS_PROVIDER) || lm.isProviderEnabled(LocationManager.NETWORK_PROVIDER);
```

@c19354837 Hi, I have one question shouldn't it be && instead of || when checking if location is enabled? I have problem with `isLocationEnabled` because I think in xiaomi I can turn off gps but still have network on?

**Comment by c19354837** [comment]
`LocationManager.NETWORK_PROVIDER` is different from the `Network`, and it's just one of Location Mode, see [this issue](https://github.com/c19354837/react-native-system-setting/issues/35)
