### ISSUE TITLE
android.permission.WRITE_SETTINGS

### ISSUE THREAD

**Issue by BennyTian** [c19354837/react-native-system-setting#6]
crash when call SystemSetting.setBrightnessForce(0.1);

exception:
`com.xxx was not granted this permission: android.permission.WRITE_SETTINGS`

RN: 0.48.4
ANDROID: 7.0

AndroidManifest.xml:

`
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.BLUETOOTH"/>
    <uses-permission android:name="android.permission.READ_LOGS" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.GET_TASKS" />
    <uses-permission android:name="android.permission.SET_DEBUG_APP" />
    <uses-permission android:name="android.permission.GET_ACCOUNTS" />
    <uses-permission android:name="android.permission.USE_CREDENTIALS" />
    <uses-permission android:name="android.permission.MANAGE_ACCOUNTS" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.RECORD_AUDIO"/>
    <uses-permission android:name="android.permission.READ_CONTACTS"/>
    <uses-permission android:name="android.permission.READ_PROFILE"/>
    <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.WRITE_SETTINGS"/>
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.webkit.permission.PLUGIN" />
    <uses-permission android:name="android.permission.SEND_SMS" />
    <uses-permission android:name="android.permission.READ_SMS" />
    <uses-permission android:name="android.permission.CALL_PHONE" />
`

thanks a lot.

**Comment by c19354837** [comment]
This permission may be blocked by system.  

You can check your app's permissions in Setting. [Follow this](https://support.google.com/googleplay/answer/6270602?) at `Turn permissions on or off`.

Also, I'll consider to check the permission at runtime in the next version.

**Comment by BennyTian** [comment]
@c19354837 

my build.gradle:

`
compileSdkVersion 24
    buildToolsVersion "24.0.3"

    dexOptions {
        jumboMode = true
    }
    
    defaultConfig {
        applicationId "com.huabenapp"
        minSdkVersion 16
        targetSdkVersion 24
`

sorry  我要说中文了...

当 build.gradle 内的 compileSdkVersion 为 24的时候,会有问题, 您的例子里的是22, 24的话,改变了授权方式 ...

最后: 大概什么时候会出 下个版本呢? 坐等哈 

感谢作者无私的奉献 ...

**Comment by c19354837** [comment]
代码已经提交，但目前手上没有Android 6+手机，明天找机器测试下再发布新版本

**Comment by c19354837** [comment]
V 1.1.0 has published

**API change:**

`setScreenMode(val)`, `setBrightness(val)` or `setBrightnessForce(val)` will return a promise

add a new API `grantWriteSettingPremission()`

All changes are forward compatible

**usage**

```javascript
const result = await SystemSetting.setBrightnessForce(value)
!result && Alert.alert('Permission Deny', 'You have no permission changing settings',[
	{'text': 'Ok', style: 'cancel'},
	{'text': 'Open Setting', onPress:()=>SystemSetting.grantWriteSettingPremission()}
])
```

[example](https://github.com/c19354837/react-native-system-setting/tree/master/examples/SystemSettingExample) and [API](https://github.com/c19354837/react-native-system-setting/wiki/API) have updated

**Comment by BennyTian** [comment]
@c19354837   thanks a lot   ！
感谢！  么么哒！！！

**Comment by c19354837** [comment]
V1.1.1 is available.

new APIs for Android brightness: `setAppBrightness(val)` `getAppBrightness()`. You can change app's brightness without any permission. [see CHANGELOG](https://github.com/c19354837/react-native-system-setting/blob/master/CHANGELOG.md)
