### ISSUE TITLE
How to save the Xcode preprocessor macros to GitHub ?

### ISSUE THREAD

**Issue by zer0nim** [c19354837/react-native-system-setting#61]
Hello,

I need to access `addBluetoothListener()` in my RN IOS application.
I know I need to add the preprocessor macros `BLUETOOTH` in Xcode to enable it.

![ios_bluetooth](https://user-images.githubusercontent.com/13215654/47445348-ff2e9f80-d7b8-11e8-8f80-3c6cdf22b659.png)

The `react-native-system-setting` `.pbxproj` is stored in the `node_modules/react-native-system-setting` folder that of course, I don' t store in GitHub.

So, I can't find a way to save the `preprocessor macros settings` in my GitHub project to avoid having to reconfigure it at every `git clone`

Or maybe if I can run a command to set the setting programmatically?

I have seen that I can also specify it with a `.xcconfig` file and `GCC_PREPROCESSOR_DEFINITIONS` but I also need to change setting to `.pbxproj` to enable the `.xcconfig` file

**Comment by c19354837** [comment]
Thanks for your feedback!

I haven't found a prefect solution for it. Even if I enable the `.xcconfig`, you still have to change the `.xcconfig` file.

I have two bad solutions:
1. You can write a `.sh` or `.bat` which will change the `.pbxproj`.
2. Fork this lib, then submit a new `.pbxproj` which contains `BLUETOOTH`. So you can reference codes by url in your `package.json`.  eg `"react-native-system-setting": "git+https://github.com/c19354837/react-native-system-setting.git#575d5b1"`

**Comment by zer0nim** [comment]
Thanks for the rapid answer!

I have finally created a script to add it automatically for the moment.
I call this script in my `package.json` `postinstall script` and its working 🎉
```
#!/bin/bash

regDebug='buildSettings = {[ \t\n]*GCC_PREPROCESSOR_DEFINITIONS = \((\n|.)*?\)\;'
replaceDebug='buildSettings = {\n\t\t\t\tGCC_PREPROCESSOR_DEFINITIONS = \(\n\t\t\t\t\t"BLUETOOTH",\n\t\t\t\t\t"DEBUG=1",\n\t\t\t\t\t"\$\(inherited\)",\n\t\t\t\t\);'

regRelease='buildSettings = {[ \t\n]*GCC_PREPROCESSOR_DEFINITIONS = "";'
replaceRelease='buildSettings = {\n\t\t\t\tGCC_PREPROCESSOR_DEFINITIONS = "BLUETOOTH";'

systSettPath='../node_modules/react-native-system-setting/ios/RCTSystemSetting.xcodeproj'

perl -0777pi -e "s/$regDebug/$replaceDebug/s" $systSettPath/project.pbxproj
perl -0777pi -e "s/$regRelease/$replaceRelease/s" $systSettPath/project.pbxproj
```
