### ISSUE TITLE
Compiled for deployment target 10.3

### ISSUE THREAD

**Issue by a-koka** [c19354837/react-native-system-setting#7]
Is it necessary to compile this for targets 10.3 and higher? I'm using over 25 libs and this is the only lib that requires me to update my target devices. Already having people complaining about not being to update to the latest version as they're not on OS 10.3 or higher.

**Comment by c19354837** [comment]
Of course not. You can change the target to any value.

**Comment by a-koka** [comment]
Thanks for the quick response @c19354837 . I should have been clearer by mentioning that perhaps we should change the repository to use 9.0 as the deployment target. It's the default for react-native and seems to be quite the standard. It's an extremely simple change and I'm happy to provide a PR if you'd like.

**Comment by c19354837** [comment]
Any PR will be welcome.

[React-native supported operating systems are >= Android 4.1 (API 16) and >= iOS 8.0.](https://github.com/facebook/react-native)

So, 8.0 is better

**Comment by c19354837** [comment]
V1.1.1 is available.
 
And I have changed the target to 8.0.
