### ISSUE TITLE
iOS: RCTEventEmitter.h not found, maybe react is old version ?

### ISSUE THREAD

**Issue by Gys** [c19354837/react-native-system-setting#71]
I get an error while building for ios: file <react/RCTEventEmitter.h> is not found. 

This file is refered to in RTCSystemSetting.h

Strange its not found, because <react/RCTBridgeModule.h> (one line before) is found with no problem (although I had to change to "RCTBridgeModule.h").

Searching in my project folder, I find indeed twice a file RCTBridgeModule.h, but nowhere a file named RCTEventEmitter.h ?!

Maybe related:
if I run 'pod install' then I get a warning at the end stating '[!] React has been deprecated'

So I wonder if there is some kind of minimum version required ? Or version conflict ?

My versions:

Podfile.lock
  - RCTSystemSetting (1.7.0):
    - React
  - React (0.11.0):
    - React/Core (= 0.11.0)
  - React/Core (0.11.0)

package.json
  - "react-native-system-setting": "^1.7.0"
  - "react-native": "0.55.4"

**Comment by Gys** [comment]
Yes I looked up the problem yesterday and tried several possible solutions, but none solved it. I also came across those solutions.

I just had another look at it.

What I do not understand is the dependence of react-native-system-setting on React/Core 0.11 ? This seems like an old version, which has a RCTBridgeModule.h file, but NOT a RCTEventEmitter.h file. So I think that is why xcode finds the first one and not the second one.

The react native xcode project itself also contains a react xcode project. That react project seems newer: it has more files, including a RCTEventEmitter.h and RCTEventEmitter.m...

I suspect xcode only finds the react project that is installed as part of the pod install. 

So why did you use that specific version ? Is it not possible to use the already installed version as part of the react native xcode project ?

Sorry for all this guessing. I have absolutely no knowledge of xcode and the inner workings of react native...

**Comment by Gys** [comment]
I also tried to run on Android. Buidling is fine, but running gives an error in metro bundler. It seems to be related to the ios problem:

error: bundling failed: ambiguous resolution: module `/Users/xxx/Projects_react_native/yyy/index.android.js` tries to require `react-native`, but there are several files providing this module. You can delete or fix them: 

  * `/Users/xxx/Projects_react_native/yyy/ios/Pods/React/package.json`
  * `/Users/xxx/Projects_react_native/yyy/node_modules/react-native/package.json`

 BUNDLE  [android, dev] ./index.android.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.

**Comment by c19354837** [comment]
I just create a new project by `react-native init xxx`, and here is my `Podfile` in `ios/`:

```ruby
react_native_path = '../node_modules/react-native'
platform :ios, '9.0'
target "xxx" do
    use_frameworks!
    
    pod 'React', :path => react_native_path, :subspecs => [
        'Core',
        'CxxBridge',
        'DevSupport',
        'RCTNetwork',
        'RCTWebSocket'
    ]
    pod 'yoga', :path => react_native_path + '/ReactCommon/yoga'
    pod 'Folly', :podspec => react_native_path + '/third-party-podspecs/Folly.podspec'

    pod 'RCTSystemSetting', :path => '../node_modules/react-native-system-setting'
end
```

It works fine.

**Comment by Gys** [comment]
Very different from my Podfile. This installs React 0.55.4 :-)
I had to remove `use_frameworks!` because it created problems with Firebase, but otherwise no real problems.
Good thinking and problem solving.
Impressive !
