### ISSUE TITLE
[Question] Proper use of setScreenMode & getScreenMode

### ISSUE THREAD

**Issue by eduardopelitti** [c19354837/react-native-system-setting#77]
Hi,

I'm implementing a functionality to increase screen brightness upon displaying QR codes from an application.

I was having problems with the getBrightness method and then I realized I was testing on Android 8.1, which apparently has problems with the screen Mode automatically setting values, and the suggested fix on another question was to `setScreenMode` to Manual.

However, this doesn't seem to have any effect on the brightness (I'm always getting the same value `0.30588` even though I'm changing it from full to zero from the native brightness slider) and when retrieving the values using `getScreenMode` I'm receiving an object as: `{ _40: 0, _65: 0, _55: null, _72: null}`. I get the same object after setting screenMode from 1 to 0, passing it like: `SystemSetting.setScreenMode(0)`.

Is there more information that we should be aware of? Is this the proper use of setScreenMode? What are the values I'm seeing when logging getScreenMode?

I couldn't find any more info on the Docs or in the code regarding these functions.

Any help appreciated! 
Thanks in advance

**Comment by c19354837** [comment]
Have you solved it yet?

`getScreenMode()` will return a Promise which contains an integer value, while you get `{ _40: 0, _65: 0, _55: null, _72: null}`.

Can you paste some codes here?

**Comment by eduardopelitti** [comment]
Hi c19354837, thanks for your answer!

When reviewing the code to add more info to this question I found the issue with the object returned from getScreenMode(). I wasn't waiting for the promise but instead I was returning the value immediately, which wasn't ready thus receiving the incorrect object:

```
await SystemSetting.getScreenMode().then(value => {
    console.warn('Current screenMode is: ', value) // This returns 1 or 0
})

console.warn('Without waiting for Promise: ', SystemSetting.getScreenMode()) // This returns { _40: 0, _65: 0, _55: null, _72: null}
```

So lesson learnt there (_if it returns a Promise, **then** wait for the Promise_). So I feel really silly about this now.

On the other hand, apparently I'm unable to change the screenMode on a device with Android 8.1, when doing:

```
  async componentDidMount() {
    await SystemSetting.setScreenMode(0)
    await SystemSetting.getScreenMode().then(value => {
      // eslint-disable-next-line no-console
      console.warn('Current screenMode is: ', value)
    })
  }
```

I always get screenMode value as `1` (on Android 8.1)

I added `<uses-permission android:name="android.permission.WRITE_SETTINGS" />` to Android Manifest. I will continue troubleshooting this on my own...If I find a pattern or an answer I'll let you know.

I'm going to assume that these are all very specific issues of my setup. I think you could close the question or mark it as resolved.

Thanks for your time and the time invested in the making the library.

Best regards!

**Comment by c19354837** [comment]
I'm glad to receive your reply.

You can change your code like this:

```js
async componentDidMount() {
  const isSuccess = await SystemSetting.setScreenMode(0)
  if (isSuccess) {
    const currentScreenMode = await SystemSetting.getScreenMode()
    console.warn('Current screenMode is: ', currentScreenMode)
  } else {
    console.warn('Permission Deny')
  }
}
```

> These codes have not been testing, but it should work.
