### ISSUE TITLE
[Question] Is it possible to extend this to support notification | do not disturb settings?

### ISSUE THREAD

**Issue by RossKinsella** [c19354837/react-native-system-setting#78]
I'm interesting in being able to programatically configure:
1) notification settings on a per app installed on the device basis
2) do not disturb status

Would something like this be theoretically possible? If so, please suggest some steps to get started on it and I'll submit a PR

Thanks!

**Comment by c19354837** [comment]
You need read the official document to find some APIs which can control notification or anything else.

For example, [LocationManager](https://developer.android.com/reference/android/location/LocationManager) is the key for get/set location status in Android.

**Comment by RossKinsella** [comment]
Gotcha. I'll look into this:
https://developer.android.com/reference/android/service/notification/ZenPolicy.Builder
