### ISSUE TITLE
Airplane Mode?

### ISSUE THREAD

**Issue by Noitidart** [c19354837/react-native-system-setting#8]
Is it possible to get support for airplane mode?

**Comment by c19354837** [comment]
I think the answer is yes.

I just need some time to confirm that it works in both Android and iOS.

**Comment by c19354837** [comment]
I think the answer is yes.

I just need some time to confirm that it works in both Android and iOS.

**Comment by Noitidart** [comment]
So so so cool thank you sir for such a fast reply and such an optimistic one!!

**Comment by c19354837** [comment]
V 1.2.0 is what you need.

new API: `isAirplaneEnabled()` & `switchAirplane(complete)`

[API](https://github.com/c19354837/react-native-system-setting/blob/master/API.md)  and [example](https://github.com/c19354837/react-native-system-setting/tree/master/examples/SystemSettingExample) are updated.

**Comment by Noitidart** [comment]
Toooo cool thank you so much! Thanks very much for also leaving this open for me to close! <3
