### ISSUE TITLE
React Native How to Set Phone Ring and Call Volume ) on Button Click

### ISSUE THREAD

**Issue by komal1212** [c19354837/react-native-system-setting#80]

**Comment by komal1212** [comment]
Can anyone have a idea about it  i refer react-native-system setting but  there is slider but i want that on buttonclick

**Comment by c19354837** [comment]
The key api is  `SystemSetting.setVolume()` and you codes may look like :

```js
let volume = 0.5

onClick () {
    volume += 0.1
    SystemSetting.setVolume(volume)
}
```

**Comment by komal1212** [comment]
> The key api is `SystemSetting.setVolume()` and you codes may look like :
> 
> ```js
> let volume = 0.5
> 
> onClick () {
>     volume += 0.1
>     SystemSetting.setVolume(volume)
> }
> ``` Thanks for your suggestion.but i set silent Ring and media both at a time click on silent button and after click on general button  both set to general mode.

**Comment by c19354837** [comment]
How about this:

```js
silent () {
    SystemSetting.setVolume(0, {type: 'ring'})
    SystemSetting.setVolume(0, {type: 'music'})
}
```

**Comment by komal1212** [comment]
SilentStart= async()=>{
  this.refs.toast.show('Profile changed to silent', 500);
    if (await SystemSetting.getVolume('ring')>0) {
    
      SystemSetting.setVolume(0,{ type:'ring'})
    } 
   

    if (await SystemSetting.getVolume('music')>0) {
    
      SystemSetting.setVolume(0,{ type:'music'})
    }

**Comment by komal1212** [comment]
> How about this:
> 
> ```js
> silent () {
>     SystemSetting.setVolume(0, {type: 'ring'})
>     SystemSetting.setVolume(0, {type: 'music'})
> }
> ```

Thank you for your Help.

**Comment by komal1212** [comment]
hi.
system setting not work in android version 5 but properly work in android
version 10.is there any solution of it for work in android version 5?

**Comment by c19354837** [comment]
I have tested the code in Android 5.1, and it works fine. I need more info about your problem

**Comment by komal1212** [comment]
still now i am checking this code in emulator Nexus_5X_API_29_x86 but when
i install my apk in phone cannot work.i do with button click
SilentStart= async()=>{
this.refs.toast.show('Profile changed to silent');
if (await SystemSetting.getVolume('ring')>0) {
SystemSetting.setVolume(0,{ type:'ring'})
}
if (await SystemSetting.getVolume('music')>0) {
SystemSetting.setVolume(0,{ type:'music'})
}
}

**Comment by komal1212** [comment]
please give me solution.

**Comment by komal1212** [comment]
Hello.there is any different steps to add map in react native version 0.6?
Because I don’t show anything in it just show me blank screen . Please
reply me as soon as possible .
