### ISSUE TITLE
registerReceiver(volumeBR, filter)

### ISSUE THREAD

**Issue by Tgoing** [c19354837/react-native-system-setting#9]
android的registerReceiver(volumeBR, filter)后是不是要注销

**Comment by c19354837** [comment]
看了下代码，之前图简单，用的全局的方式实现，这样 js 端写起来也很方便

你是有遇到什么问题么

**Comment by Tgoing** [comment]
暂时还看不出来，只是听说没有注销android是不会去销毁它的，可能会造成内存泄漏，我也是刚看android的广播

**Comment by c19354837** [comment]
Android 中确实是有销毁的需求。针对动态注册广播，注册和注销成对出现是一个良好的编程实践，有效避免重复注册或者因为生命周期不一致出现的问题

而结合 RN 实际来看，这个模块应该是单例的，那么就更像是在 AndroidManifest 文件中声明的全局广播，随着应用的销毁而释放资源

**Comment by Tgoing** [comment]
是RN会去销毁它吗？

**Comment by c19354837** [comment]
系统回收资源

**Comment by Tgoing** [comment]
哦，好的，谢谢
